I am interested to learn linear function like y = x**2

In [75]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf
x = tf.placeholder(shape=[4,1], dtype=tf.float32)
y_true=tf.placeholder(shape=[4,1],dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x)

loss = tf.losses.mean_squared_error(y_true,y_pred)
train = tf.train.AdamOptimizer(learning_rate=1.5).minimize(loss)

input_x = input_x = np.random.randint(5, size=(4, 1))
input_y = input_x**2
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print("Loss:\n")
    for i in range(1000):
        _,losses,y_pred1=sess.run((train,loss,y_pred),{x: input_x,y_true:input_y})
        if i%100 ==0:
            pass
            print(losses)
    print("Predicted Values,Actual_values \n",np.array(zip(y_pred1,input_y)))


Loss:

53.9268
0.251213
0.25
0.25
0.25
0.25
0.25
0.25
0.25
0.25
Predicted Values,Actual_values 
 [[[ 0.5]
  [ 1. ]]

 [[ 4.5]
  [ 4. ]]

 [[ 8.5]
  [ 9. ]]

 [[ 4.5]
  [ 4. ]]]
